#!/usr/bin/env ruby

require 'capwatch'
include Capwatch

options = CLI.parse(ARGV)
capwatch_file = File.expand_path('~/.capwatch')
fund = JSON.parse(File.open(capwatch_file).read)

loop do
  table = Calculator.fund_hash(fund, CoinMarketCap.fetch)
  system('clear')
  puts Console.draw_table(table)
  sleep options.tick
end
