#!/usr/bin/env ruby

require 'capwatch'
include Capwatch

options = CLI.parse(ARGV)

if options.telegram
  Telegram.new(token: options.telegram).start
else
  loop do
    table = Calculator.fund_hash(FundParser.new.fund, CoinMarketCap.fetch)
    system('clear')
    puts Console.draw_table(table)
    sleep options.tick
  end
end
